name: Deploy Link Builder App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy Client
        run: |
          cd client
          npm install
          npm run build
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/client/dist/ ${{ secrets.USER_SECRET }}@${{ secrets.SERVER_IP_SECRET }}:/var/www/clickstrawl.com

      - name: Build and Deploy Server
        run: |
          cd server
          npm install
          npm run build
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/server/dist/ ${{ secrets.USER_SECRET }}@${{ secrets.SERVER_IP_SECRET }}:/var/www/cltrwl.com
          
      - name: Restart Backend with PM2
        run: ssh ${{ secrets.USER_SECRET }}@${{ secrets.SERVER_IP_SECRET }} 'pm2 restart ${{ secrets.BACKEND_APP_NAME_SECRET }}'
